#1/bin/sh

# cleanup
rm -rf obj_dir
rm -f auto_f1_fsm.ved

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace  auto_f1_fsm.sv f1_fsm.sv clktick.sv --exe auto_f1_fsm_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vauto_f1_fsm.mk Vauto_f1_fsm

# run executable simulation file
obj_dir/Vauto_f1_fsm